server:
  port: 8081

spring:
  application:
    name: auth-service
  profiles:
    active: dev

jwt:
  secret: ${JWT_SECRET:3bZ4bR0S5c7hFQ2nTzF8oQv9vKxM2yP7aLw8eJrHkU1cNdWqXyZp6tR9mVb4sL0Q8nF5gH2kJ3lP6rS9uVw==}
  expiration: ${JWT_EXPIRATION:30m}

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.sql: DEBUG
    pe.albrugroup.auth_service: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
