package pe.albrugroup.rrhh_service.entity.enums;

public enum PuestoTrabajo {
    ADMINISTRADOR,
    RRHH,
    RECLUTADOR,
    CAPACITADOR,
    DESARROLLADOR,
    CONTADOR,
    COMMUNITY,
    MONITOR,
    SUPERVISOR_VENTAS,
    ASESOR_VENTAS,
    OJT,
    SUPERVISOR_BACKOFFICE,
    ASESOR_BACKOFFICE,
    SUPERVISOR_GTR,
    ASESOR_GTR,
    SUPERVISOR_POSTVENTA,
    ASESOR_POSTVENTA,
    ASESOR_COBRANZA
}
