package pe.albrugroup.rrhh_service.entity.enums;

public enum ReclutamientoSubEstado {
    NO_DESEA_PUESTO,
    NO_ASISTIO_MEET,
    POCA_FLUIDEZ_VERBAL,
    SIN_HABILIDADES_COMERCIALES,
    INEXPERIENCIA,
    PROBLEMAS_CON_HORARIOS,
    DISTANCIA_TIEMPO,
    BENEFICIOS_PLANILLA,
    SALARIO_BASE,
    MALA_EXPERIENCIA,
    RUBRO_DE_LA_EMPRESA,
    RECIBIO_MEJOR_PROPUESTA
}
