package pe.albrugroup.recruitment_service.entity.enums;

public enum Accion {
    REGISTRO_POSTULACION,
    ACTUALIZACION_POSTULACION,
    CONTACTO,
    TIPIFICACION,
    ASIGNACION_GRUPO_CAPACITACION,
    APROBACION_CAPACITACION,
    DESAPROBACION_CAPACITACION,
    CONFIRMACION_CONTRATACION
}
