create table planilla_general (
    id bigint generated by default as identity primary key,
    anio integer not null,
    mes integer not null,
    tipo_planilla varchar(40) not null,
    estado varchar(40) not null,
    moneda varchar(3) not null,
    version_calculo integer not null,
    approved_at timestamp with time zone,
    approved_by varchar(255),
    total_gasto_planilla numeric(14, 2) not null,
    total_descuentos numeric(14, 2) not null,
    total_bonificaciones numeric(14, 2) not null,
    cantidad_empleados integer not null,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    constraint uk_planilla_general_periodo_tipo unique (anio, mes, tipo_planilla)
);

create table planilla_empleado (
    id bigint generated by default as identity primary key,
    id_planilla_general bigint not null,
    id_empleado bigint not null,
    nombres varchar(255) not null,
    apellidos varchar(255) not null,
    tipo_documento varchar(40) not null,
    numero_documento varchar(50) not null,
    modalidad_dominante varchar(40) not null,
    multiple_tramos boolean not null,
    sueldo_basico numeric(14, 2) not null,
    dias_mes integer not null,
    dias_habiles integer not null,
    pago_dia_habil numeric(14, 2) not null,
    fecha_ingreso date not null,
    fecha_baja date,
    dias_validos integer not null,
    sueldo_afecto numeric(14, 2) not null,
    tardanzas integer not null,
    faltas_injustificadas integer not null,
    descuento_tardanzas numeric(14, 2) not null,
    descuento_faltas numeric(14, 2) not null,
    adelanto_sueldo numeric(14, 2) not null,
    total_descuento numeric(14, 2) not null,
    ventas_validas integer not null,
    bono_productividad numeric(14, 2) not null,
    bono_puntualidad numeric(14, 2) not null,
    bono_capacitacion numeric(14, 2) not null,
    minutos_extras integer not null,
    pago_extras numeric(14, 2) not null,
    total_bonificaciones numeric(14, 2) not null,
    remuneracion_neta numeric(14, 2) not null,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    constraint fk_planilla_empleado_planilla foreign key (id_planilla_general) references planilla_general (id),
    constraint uk_planilla_empleado unique (id_planilla_general, id_empleado)
);

create table tramo_planilla_empleado (
    id bigint generated by default as identity primary key,
    id_planilla_empleado bigint not null,
    id_contrato bigint not null,
    fecha_inicio_contrato date not null,
    fecha_fin_contrato date,
    fecha_desde_tramo date not null,
    fecha_hasta_tramo date not null,
    modalidad_trabajo varchar(40) not null,
    sueldo_basico numeric(14, 2) not null,
    horas_dia integer not null,
    dias_validos integer not null,
    pago_dia_habil numeric(14, 2) not null,
    sueldo_afecto numeric(14, 2) not null,
    tardanzas integer not null,
    faltas_injustificadas integer not null,
    descuento_tardanzas numeric(14, 2) not null,
    descuento_faltas numeric(14, 2) not null,
    minutos_extras integer not null,
    pago_extras numeric(14, 2) not null,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    constraint fk_tramo_planilla_empleado foreign key (id_planilla_empleado) references planilla_empleado (id)
);

create table detalle_planilla (
    id bigint generated by default as identity primary key,
    id_planilla_empleado bigint not null,
    id_tramo_planilla_empleado bigint,
    concepto varchar(60) not null,
    tipo_movimiento varchar(40) not null,
    descripcion varchar(255) not null,
    fecha_referencia date,
    cantidad numeric(14, 2),
    tarifa numeric(14, 2),
    monto numeric(14, 2) not null,
    fuente varchar(80) not null,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    constraint fk_detalle_planilla_empleado foreign key (id_planilla_empleado) references planilla_empleado (id),
    constraint fk_detalle_tramo_planilla foreign key (id_tramo_planilla_empleado) references tramo_planilla_empleado (id)
);

create table adelanto_sueldo (
    id bigint generated by default as identity primary key,
    id_empleado bigint not null,
    anio integer not null,
    mes integer not null,
    monto numeric(14, 2) not null,
    descripcion varchar(255) not null,
    registrado_por varchar(255),
    registrado_at timestamp with time zone
);

create index idx_planilla_empleado_id_empleado on planilla_empleado (id_empleado);
create index idx_tramo_planilla_empleado on tramo_planilla_empleado (id_planilla_empleado);
create index idx_detalle_planilla_empleado on detalle_planilla (id_planilla_empleado);
create index idx_adelanto_sueldo_periodo on adelanto_sueldo (anio, mes, id_empleado);
