create table matriz_calculo_planilla (
    id bigint generated by default as identity primary key,
    version integer not null,
    activa boolean not null,
    bono_capacitacion numeric(14, 2) not null,
    comentario varchar(255),
    creado_por varchar(255),
    creado_at timestamp with time zone,
    constraint uk_matriz_calculo_planilla_version unique (version)
);

create table matriz_modalidad_planilla (
    id bigint generated by default as identity primary key,
    id_matriz_calculo bigint not null,
    modalidad varchar(40) not null,
    horas_dia integer not null,
    bono_puntualidad numeric(14, 2) not null,
    ventas_minimas_productividad integer not null,
    bono_productividad numeric(14, 2) not null,
    constraint fk_matriz_modalidad_calculo foreign key (id_matriz_calculo) references matriz_calculo_planilla (id),
    constraint uk_matriz_modalidad unique (id_matriz_calculo, modalidad)
);

create table matriz_tardanza_planilla (
    id bigint generated by default as identity primary key,
    id_matriz_calculo bigint not null,
    minutos_desde integer not null,
    minutos_hasta integer not null,
    monto_descuento numeric(14, 2) not null,
    constraint fk_matriz_tardanza_calculo foreign key (id_matriz_calculo) references matriz_calculo_planilla (id),
    constraint uk_matriz_tardanza unique (id_matriz_calculo, minutos_desde, minutos_hasta)
);

create table bono_adicional_empleado (
    id bigint generated by default as identity primary key,
    id_empleado bigint not null,
    anio integer not null,
    mes integer not null,
    monto numeric(14, 2) not null,
    comentario varchar(255) not null,
    registrado_por varchar(255),
    registrado_at timestamp with time zone
);

alter table planilla_general
    add column id_matriz_calculo bigint;

alter table planilla_empleado
    add column bono_adicional numeric(14, 2) not null default 0.00;

insert into matriz_calculo_planilla (version, activa, bono_capacitacion, comentario, creado_por, creado_at)
values (1, true, 50.00, 'Matriz inicial creada desde reglas V1', 'SYSTEM', current_timestamp);

insert into matriz_modalidad_planilla (
    id_matriz_calculo,
    modalidad,
    horas_dia,
    bono_puntualidad,
    ventas_minimas_productividad,
    bono_productividad
)
select m.id, v.modalidad, v.horas_dia, v.bono_puntualidad, v.ventas_minimas_productividad, v.bono_productividad
from matriz_calculo_planilla m
cross join (
    values
        ('PARTTIME', 4, 50.00, 30, 100.00),
        ('SEMIFULLTIME', 6, 100.00, 40, 100.00),
        ('FULLTIME', 8, 100.00, 60, 100.00),
        ('SUPERFULLTIME', 10, 100.00, 60, 100.00)
) as v(modalidad, horas_dia, bono_puntualidad, ventas_minimas_productividad, bono_productividad)
where m.version = 1;

insert into matriz_tardanza_planilla (id_matriz_calculo, minutos_desde, minutos_hasta, monto_descuento)
select m.id, v.minutos_desde, v.minutos_hasta, v.monto_descuento
from matriz_calculo_planilla m
cross join (
    values
        (5, 9, 5.00),
        (10, 20, 10.00)
) as v(minutos_desde, minutos_hasta, monto_descuento)
where m.version = 1;

update planilla_general
set id_matriz_calculo = (select id from matriz_calculo_planilla where version = 1)
where id_matriz_calculo is null;

alter table planilla_general
    alter column id_matriz_calculo set not null;

alter table planilla_general
    add constraint fk_planilla_general_matriz_calculo foreign key (id_matriz_calculo) references matriz_calculo_planilla (id);

create index idx_bono_adicional_empleado_periodo on bono_adicional_empleado (anio, mes, id_empleado);
