; ============================================================================
; http.conf - HTTP server interno (necesario para ARI y WebRTC vias WS)
; ============================================================================
[general]
enabled = yes
bindaddr = 0.0.0.0
bindport = 8088
; Para Fase 1 dejamos HTTP plano. En Fase 2 se habilita TLS con cert real.
tlsenable = no
; tlsbindaddr = 0.0.0.0:8089
; tlscertfile = /etc/asterisk/keys/asterisk.pem
; tlsprivatekey = /etc/asterisk/keys/asterisk.key
prefix =
session_keep_alive = 15000
session_inactivity = 30000
