; ============================================================================
; rtp.conf - Rango de puertos para audio RTP
; ============================================================================
[general]
rtpstart = 10000
rtpend = 10500
strictrtp = yes
probation = 4
icesupport = yes
