spring:
  data:
    redis:
      host: ${LEAD_REDIS_HOST:localhost}
      port: ${LEAD_REDIS_PORT:6379}
      timeout: 2000ms
  datasource:
    url: jdbc:h2:mem:leaddb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.sql: DEBUG
    pe.albrugroup.lead_service: DEBUG
