; ============================================================================
; logger.conf - Configuracion de logs
; ============================================================================
[general]
dateformat = %F %T.%3q
queue_log = yes
queue_log_name = queue_log

[logfiles]
console => notice,warning,error,verbose(3)
messages => notice,warning,error
full => notice,warning,error,debug,verbose,dtmf
