export const OPERATIONAL_ROLES: ReadonlySet<string> = new Set([
  'ASESOR_VENTAS',
  'ASESOR_GTR',
  'SUPERVISOR_VENTAS',
  'ASESOR_BACKOFFICE',
  'SUPERVISOR_BACKOFFICE',
  'ASESOR_POSTVENTA',
  'SUPERVISOR_POSTVENTA',
  'OJT'
]);
