spring:
  data:
    redis:
      host: ${GATEWAY_REDIS_HOST:localhost}
      port: ${GATEWAY_REDIS_PORT:6379}
      timeout: 2000ms
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - ${FRONTEND_URL}
                allowedMethods:
                  - GET
                  - POST
                  - PATCH
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
