server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: rrhh-service
          uri: http://localhost:8082
          predicates:
            - Path=/rrhh/**
        - id: lead-service
          uri: http://localhost:8083
          predicates:
            - Path=/leads/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
jwt:
  secret: tu-clave-secreta-super-segura-de-al-menos-256-bits-para-HS256

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG