server:
  port: 8082

spring:
  application:
    name: rrhh-service
  profiles:
    active: dev

jwt:
  secret: ${JWT_SECRET:3bZ4bR0S5c7hFQ2nTzF8oQv9vKxM2yP7aLw8eJrHkU1cNdWqXyZp6tR9mVb4sL0Q8nF5gH2kJ3lP6rS9uVw==}

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.sql: DEBUG
    pe.albrugroup.rrhh_service: DEBUG

services:
  auth:
    base-url: ${AUTH_SERVICE_URL:http://localhost:8081}
  recruitment:
    base-url: ${RECRUITMENT_SERVICE_URL:http://localhost:8084}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
