/**
 * Datos simulados para la aplicación
 */

import type { Employee, Statistic, UserProfile } from '../types';

export const mockEmployees: Employee[] = [
  {
    id: '1',
    initials: 'AJ',
    fullName: 'Alex Johnson',
    position: 'Supervisor de Ventas',
    department: 'Ventas',
    status: 'ACTIVO',
    documentType: 'DNI',
    documentNumber: '87654321',
    nationality: 'Peruana',
    birthDate: '1982-08-08',
    civilStatus: 'Soltero',
    hasChildren: false,
    district: 'Independencia',
    address: 'casa',
    phoneFixed: '546321',
    phoneMobile: '987654321',
    phoneWork: '963258741',
    personalEmail: 'juancito@gmail.com',
    bank: 'BCP',
    accountNumber: '15623651894',
    interbankNumber: '11851256168515168',
    startDate: '2026-01-01',
    endDate: '2026-02-01',
    modality: 'PART TIME',
    scheduleType: 'PRESENCIAL',
    googleEmail: 'jclementc@albru.pe',
  },
  {
    id: '2',
    initials: 'MG',
    fullName: 'María García',
    position: 'Supervisor Backoffice',
    department: 'Backoffice',
    status: 'ACTIVO',
    documentType: 'DNI',
    documentNumber: '45678901',
    nationality: 'Peruana',
    birthDate: '1985-05-15',
    civilStatus: 'Casada',
    hasChildren: true,
    district: 'San Isidro',
    address: 'Av. Principal 123',
    phoneFixed: '456789',
    phoneMobile: '987654322',
    phoneWork: '963258742',
    personalEmail: 'maria.garcia@gmail.com',
    bank: 'Interbank',
    accountNumber: '15634651895',
    interbankNumber: '11851256168515170',
    startDate: '2025-03-15',
    endDate: '',
    modality: 'PART TIME',
    scheduleType: 'PRESENCIAL',
    googleEmail: 'mgarcia@albru.pe',
  },
  {
    id: '3',
    initials: 'JW',
    fullName: 'James Wilson',
    position: 'Asesor GTR',
    department: 'GTR',
    status: 'INACTIVO',
    documentType: 'Pasaporte',
    documentNumber: '12345678',
    nationality: 'Americana',
    birthDate: '1995-12-20',
    civilStatus: 'Soltero',
    hasChildren: false,
    district: 'Miraflores',
    address: 'Calle Secundaria 456',
    phoneFixed: '789456',
    phoneMobile: '987654323',
    phoneWork: '963258743',
    personalEmail: 'james.wilson@gmail.com',
    bank: 'Scotiabank',
    accountNumber: '15645651896',
    interbankNumber: '11851256168515171',
    startDate: '2024-06-01',
    endDate: '2026-02-28',
    modality: 'Contrato',
    scheduleType: 'FULL TIME',
    googleEmail: 'jwilson@albru.pe',
  },
  {
    id: '4',
    initials: 'RT',
    fullName: 'Robert Taylor',
    position: 'Asesor Postventa',
    department: 'Postventa',
    status: 'ACTIVO',
    documentType: 'DNI',
    documentNumber: '98765432',
    nationality: 'Peruana',
    birthDate: '2000-03-10',
    civilStatus: 'Soltero',
    hasChildren: false,
    district: 'Surco',
    address: 'Jr. Tercera 789',
    phoneFixed: '321654',
    phoneMobile: '987654324',
    phoneWork: '963258744',
    personalEmail: 'robert.taylor@gmail.com',
    bank: 'BBVA',
    accountNumber: '15656651897',
    interbankNumber: '11851256168515172',
    startDate: '2025-01-15',
    modality: 'SUPER FULL',
    scheduleType: 'PRESENCIAL',
    googleEmail: 'rtaylor@albru.pe',
  },
  {
    id: '5',
    initials: 'CR',
    fullName: 'Carla Rodríguez',
    position: 'Asesor RRHH',
    department: 'RRHH',
    status: 'ACTIVO',
    documentType: 'DNI',
    documentNumber: '11223344',
    nationality: 'Peruana',
    birthDate: '1988-07-22',
    civilStatus: 'Casada',
    hasChildren: true,
    district: 'La Molina',
    address: 'Av. Primavera 100',
    phoneFixed: '654321',
    phoneMobile: '987654325',
    phoneWork: '963258745',
    personalEmail: 'carla.rodriguez@gmail.com',
    bank: 'BCP',
    accountNumber: '15667651898',
    interbankNumber: '11851256168515173',
    startDate: '2024-09-01',
    modality: 'FULL TIME',
    scheduleType: 'PRESENCIAL',
    googleEmail: 'crodriguez@albru.pe',
  },
  {
    id: '6',
    initials: 'LP',
    fullName: 'Luis Pérez',
    position: 'Contador',
    department: 'Contabilidad',
    status: 'ACTIVO',
    documentType: 'DNI',
    documentNumber: '22334455',
    nationality: 'Peruana',
    birthDate: '1992-11-05',
    civilStatus: 'Soltero',
    hasChildren: false,
    district: 'San Isidro',
    address: 'Calle Principal 200',
    phoneFixed: '789123',
    phoneMobile: '987654326',
    phoneWork: '963258746',
    personalEmail: 'luis.perez@gmail.com',
    bank: 'Scotiabank',
    accountNumber: '15678651899',
    interbankNumber: '11851256168515174',
    startDate: '2025-02-10',
    modality: 'FULL TIME',
    scheduleType: 'PRESENCIAL',
    googleEmail: 'lperez@albru.pe',
  },
  {
    id: '7',
    initials: 'MH',
    fullName: 'Marta Hernández',
    position: 'Community Manager',
    department: 'Marketing',
    status: 'ACTIVO',
    documentType: 'DNI',
    documentNumber: '33445566',
    nationality: 'Peruana',
    birthDate: '1994-04-18',
    civilStatus: 'Soltera',
    hasChildren: false,
    district: 'Miraflores',
    address: 'Jr. Costanera 300',
    phoneFixed: '456789',
    phoneMobile: '987654327',
    phoneWork: '963258747',
    personalEmail: 'marta.hernandez@gmail.com',
    bank: 'BBVA',
    accountNumber: '15689651900',
    interbankNumber: '11851256168515175',
    startDate: '2025-03-05',
    modality: 'SEMI FULL',
    scheduleType: 'SEMIPRESENCIAL',
    googleEmail: 'mhernandez@albru.pe',
  },
  {
    id: '8',
    initials: 'JG',
    fullName: 'Juan García López',
    position: 'Supervisor Backoffice',
    department: 'Backoffice',
    status: 'INACTIVO',
    documentType: 'DNI',
    documentNumber: '44556677',
    nationality: 'Peruana',
    birthDate: '1987-09-12',
    civilStatus: 'Casado',
    hasChildren: true,
    district: 'Surco',
    address: 'Av. Benavides 400',
    phoneFixed: '321987',
    phoneMobile: '987654328',
    phoneWork: '963258748',
    personalEmail: 'juan.garcia@gmail.com',
    bank: 'Interbank',
    accountNumber: '15690651901',
    interbankNumber: '11851256168515176',
    startDate: '2024-05-20',
    modality: 'FULL TIME',
    scheduleType: 'PRESENCIAL',
    googleEmail: 'jgarcia@albru.pe',
  },
  {
    id: '9',
    initials: 'SV',
    fullName: 'Sandra Vargas',
    position: 'Asesor Ventas',
    department: 'Ventas',
    status: 'ACTIVO',
    documentType: 'CE',
    documentNumber: '55667788',
    nationality: 'Colombiana',
    birthDate: '1996-06-30',
    civilStatus: 'Soltera',
    hasChildren: false,
    district: 'Independencia',
    address: 'Jr. Ucayali 500',
    phoneFixed: '654987',
    phoneMobile: '987654329',
    phoneWork: '963258749',
    personalEmail: 'sandra.vargas@gmail.com',
    bank: 'BCP',
    accountNumber: '15701651902',
    interbankNumber: '11851256168515177',
    startDate: '2025-01-25',
    modality: 'PART TIME',
    scheduleType: 'PRESENCIAL',
    googleEmail: 'svargas@albru.pe',
  },
  {
    id: '10',
    initials: 'EP',
    fullName: 'Enrique Paredes',
    position: 'Asesor GTR',
    department: 'GTR',
    status: 'ACTIVO',
    documentType: 'DNI',
    documentNumber: '66778899',
    nationality: 'Peruana',
    birthDate: '1991-08-14',
    civilStatus: 'Casado',
    hasChildren: false,
    district: 'San Isidro',
    address: 'Calle Comercial 600',
    phoneFixed: '987654',
    phoneMobile: '987654330',
    phoneWork: '963258750',
    personalEmail: 'enrique.paredes@gmail.com',
    bank: 'Scotiabank',
    accountNumber: '15712651903',
    interbankNumber: '11851256168515178',
    startDate: '2024-12-01',
    modality: 'FULL TIME',
    scheduleType: 'PRESENCIAL',
    googleEmail: 'eparedes@albru.pe',
  },
  {
    id: '11',
    initials: 'AG',
    fullName: 'Amanda González',
    position: 'Asesor Postventa',
    department: 'Postventa',
    status: 'ACTIVO',
    documentType: 'DNI',
    documentNumber: '77889900',
    nationality: 'Peruana',
    birthDate: '1993-10-28',
    civilStatus: 'Soltera',
    hasChildren: true,
    district: 'Miraflores',
    address: 'Av. Larco 700',
    phoneFixed: '123456',
    phoneMobile: '987654331',
    phoneWork: '963258751',
    personalEmail: 'amanda.gonzalez@gmail.com',
    bank: 'BBVA',
    accountNumber: '15723651904',
    interbankNumber: '11851256168515179',
    startDate: '2025-02-15',
    modality: 'SEMI FULL',
    scheduleType: 'SEMIPRESENCIAL',
    googleEmail: 'agonzalez@albru.pe',
  },
  {
    id: '12',
    initials: 'VQ',
    fullName: 'Víctor Quintero',
    position: 'Supervisor Ventas',
    department: 'Ventas',
    status: 'ACTIVO',
    documentType: 'DNI',
    documentNumber: '88990011',
    nationality: 'Peruana',
    birthDate: '1989-01-09',
    civilStatus: 'Casado',
    hasChildren: true,
    district: 'La Molina',
    address: 'Jr. Siete 800',
    phoneFixed: '234567',
    phoneMobile: '987654332',
    phoneWork: '963258752',
    personalEmail: 'victor.quintero@gmail.com',
    bank: 'BCP',
    accountNumber: '15734651905',
    interbankNumber: '11851256168515180',
    startDate: '2024-11-10',
    modality: 'FULL TIME',
    scheduleType: 'PRESENCIAL',
    googleEmail: 'vquintero@albru.pe',
  },
  {
    id: '13',
    initials: 'NL',
    fullName: 'Nadia López',
    position: 'Asesor Backoffice',
    department: 'Backoffice',
    status: 'ACTIVO',
    documentType: 'DNI',
    documentNumber: '99001122',
    nationality: 'Peruana',
    birthDate: '1997-05-16',
    civilStatus: 'Soltera',
    hasChildren: false,
    district: 'Surco',
    address: 'Pasaje Interior 900',
    phoneFixed: '345678',
    phoneMobile: '987654333',
    phoneWork: '963258753',
    personalEmail: 'nadia.lopez@gmail.com',
    bank: 'Interbank',
    accountNumber: '15745651906',
    interbankNumber: '11851256168515181',
    startDate: '2025-03-10',
    modality: 'PART TIME',
    scheduleType: 'PRESENCIAL',
    googleEmail: 'nlopez@albru.pe',
  },
  {
    id: '14',
    initials: 'FC',
    fullName: 'Fernando Castro',
    position: 'RRHH',
    department: 'RRHH',
    status: 'ACTIVO',
    documentType: 'DNI',
    documentNumber: '10111213',
    nationality: 'Peruana',
    birthDate: '1986-03-25',
    civilStatus: 'Soltero',
    hasChildren: false,
    district: 'San Isidro',
    address: 'Calle Ejecutiva 1000',
    phoneFixed: '456789',
    phoneMobile: '987654334',
    phoneWork: '963258754',
    personalEmail: 'fernando.castro@gmail.com',
    bank: 'Scotiabank',
    accountNumber: '15756651907',
    interbankNumber: '11851256168515182',
    startDate: '2024-08-20',
    modality: 'FULL TIME',
    scheduleType: 'PRESENCIAL',
    googleEmail: 'fcastro@albru.pe',
  },
  {
    id: '15',
    initials: 'RM',
    fullName: 'Rosa Mendoza',
    position: 'Supervisor Postventa',
    department: 'Postventa',
    status: 'INACTIVO',
    documentType: 'DNI',
    documentNumber: '11121314',
    nationality: 'Peruana',
    birthDate: '1990-07-11',
    civilStatus: 'Casada',
    hasChildren: true,
    district: 'Miraflores',
    address: 'Av. Diagonal 1100',
    phoneFixed: '567890',
    phoneMobile: '987654335',
    phoneWork: '963258755',
    personalEmail: 'rosa.mendoza@gmail.com',
    bank: 'BBVA',
    accountNumber: '15767651908',
    interbankNumber: '11851256168515183',
    startDate: '2024-04-15',
    modality: 'FULL TIME',
    scheduleType: 'PRESENCIAL',
    googleEmail: 'rmendoza@albru.pe',
  },
];

export const mockStatistics: Statistic[] = [
  {
    label: 'TOTAL EMPLEADOS',
    value: 1248,
  },
  {
    label: 'ACTIVOS',
    value: 1200,
  },
  {
    label: 'INACTIVOS',
    value: 48,
  },
];

export const mockUserProfile: UserProfile = {
  name: 'Carlos Mendoza',
  role: 'RRHH',
  avatar: 'CM',
};

export const mockApplicants = [
  {
    id: '1',
    fullName: 'Juan Carlos López',
    phoneMobile: '987654321',
    documentType: 'DNI',
    documentNumber: '12345678',
    positionOfInterest: 'ASESOR_VENTAS',
    modality: 'PART TIME',
    campaign: 'Campaña enero 2026',
  },
  {
    id: '2',
    fullName: 'Sofía Martínez García',
    phoneMobile: '987123456',
    documentType: 'DNI',
    documentNumber: '23456789',
    positionOfInterest: 'SUPERVISOR_VENTAS',
    modality: 'SEMI FULL',
    campaign: 'Campaña enero 2026',
  },
  {
    id: '3',
    fullName: 'Roberto Fernández',
    phoneMobile: '987234567',
    documentType: 'DNI',
    documentNumber: '34567890',
    positionOfInterest: 'ASESOR_BACKOFFICE',
    modality: 'FULL TIME',
    campaign: 'Campaña febrero 2026',
  },
  {
    id: '4',
    fullName: 'Patricia Morales',
    phoneMobile: '987345678',
    documentType: 'CE',
    documentNumber: '45678901',
    positionOfInterest: 'ASESOR_VENTAS',
    modality: 'SUPER FULL',
    campaign: 'Campaña enero 2026',
  },
  {
    id: '5',
    fullName: 'David Sánchez López',
    phoneMobile: '987456789',
    documentType: 'DNI',
    documentNumber: '56789012',
    positionOfInterest: 'ASESOR_GTR',
    modality: 'PART TIME',
    campaign: 'Campaña febrero 2026',
  },
  {
    id: '6',
    fullName: 'Daniela Flores',
    phoneMobile: '987456790',
    documentType: 'DNI',
    documentNumber: '67890123',
    positionOfInterest: 'ASESOR_VENTAS',
    modality: 'FULL TIME',
    campaign: 'Campaña febrero 2026',
  },
  {
    id: '7',
    fullName: 'Cristian Rosales',
    phoneMobile: '987456791',
    documentType: 'DNI',
    documentNumber: '78901234',
    positionOfInterest: 'SUPERVISOR_BACKOFFICE',
    modality: 'SEMI FULL',
    campaign: 'Campaña marzo 2026',
  },
  {
    id: '8',
    fullName: 'Lidia Santos',
    phoneMobile: '987456792',
    documentType: 'CE',
    documentNumber: '89012345',
    positionOfInterest: 'ASESOR_POSTVENTA',
    modality: 'FULL TIME',
    campaign: 'Campaña marzo 2026',
  },
  {
    id: '9',
    fullName: 'Ángelo Ruiz',
    phoneMobile: '987456793',
    documentType: 'DNI',
    documentNumber: '90123456',
    positionOfInterest: 'ASESOR_BACKOFFICE',
    modality: 'PART TIME',
    campaign: 'Campaña enero 2026',
  },
  {
    id: '10',
    fullName: 'Marina Delgado',
    phoneMobile: '987456794',
    documentType: 'DNI',
    documentNumber: '01234567',
    positionOfInterest: 'SUPERVISOR_VENTAS',
    modality: 'FULL TIME',
    campaign: 'Campaña febrero 2026',
  },
  {
    id: '11',
    fullName: 'Oscar Navarro',
    phoneMobile: '987456795',
    documentType: 'DNI',
    documentNumber: '12345679',
    positionOfInterest: 'ASESOR_GTR',
    modality: 'SEMI FULL',
    campaign: 'Campaña marzo 2026',
  },
  {
    id: '12',
    fullName: 'Fernanda Castro',
    phoneMobile: '987456796',
    documentType: 'DNI',
    documentNumber: '23456780',
    positionOfInterest: 'COMMUNITY',
    modality: 'PART TIME',
    campaign: 'Campaña febrero 2026',
  },
  {
    id: '13',
    fullName: 'Sergio Campos',
    phoneMobile: '987456797',
    documentType: 'DNI',
    documentNumber: '34567891',
    positionOfInterest: 'ASESOR_VENTAS',
    modality: 'FULL TIME',
    campaign: 'Campaña marzo 2026',
  },
  {
    id: '14',
    fullName: 'Valeria Quispe',
    phoneMobile: '987456798',
    documentType: 'CE',
    documentNumber: '45678902',
    positionOfInterest: 'RRHH',
    modality: 'SEMI FULL',
    campaign: 'Campaña enero 2026',
  },
  {
    id: '15',
    fullName: 'Gustavo Medina',
    phoneMobile: '987456799',
    documentType: 'DNI',
    documentNumber: '56789013',
    positionOfInterest: 'CONTABILIDAD',
    modality: 'FULL TIME',
    campaign: 'Campaña febrero 2026',
  },
  {
    id: '16',
    fullName: 'Teresa Fuentes',
    phoneMobile: '987456800',
    documentType: 'DNI',
    documentNumber: '67890124',
    positionOfInterest: 'ASESOR_POSTVENTA',
    modality: 'PART TIME',
    campaign: 'Campaña marzo 2026',
  },
];

export const ITEMS_PER_PAGE = 10;
export const TOTAL_ITEMS = 1248;

export const AVAILABLE_POSITIONS_GROUPED = {
  'DESARROLLADOR': [
    'DESARROLLADOR',
  ],
  'ADMINISTRADOR': [
    'ADMINISTRADOR'
  ],
  'RRHH': [
    'RRHH',
    'CAPACITACION',
    'RECLUTAMIENTO'
  ],
  'CONTABILIDAD': ['CONTABILIDAD'],
  'COMMUNITY': ['COMMUNITY'],
  'VENTAS': [
    'SUPERVISOR_VENTAS',
    'ASESOR_VENTAS',
  ],
  'BACKOFFICE': [
    'SUPERVISOR_BACKOFFICE',
    'ASESOR_BACKOFFICE',
  ],
  'GTR': [
    'SUPERVISOR_GTR',
    'ASESOR_GTR',
  ],
  'POSTVENTA/COBRANZA/PLATAFORMA D.': [
    'SUPERVISOR_POSTVENTA',
    'ASESOR_POSTVENTA',
  ],
};

export const AVAILABLE_POSITIONS = [
  'DESARROLLADOR',
  'ADMINISTRADOR',
  'RRHH',
  'CAPACITACION',
  'RECLUTAMIENTO',
  'CONTABILIDAD',
  'COMMUNITY',
  'SUPERVISOR_VENTAS',
  'ASESOR_VENTAS',
  'SUPERVISOR_BACKOFFICE',
  'ASESOR_BACKOFFICE',
  'SUPERVISOR_GTR',
  'ASESOR_GTR',
  'SUPERVISOR_POSTVENTA',
  'ASESOR_POSTVENTA',
];

