CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TEMP TABLE seed_permisos (
    nombre TEXT PRIMARY KEY,
    descripcion TEXT NOT NULL,
    recurso TEXT NOT NULL,
    accion TEXT NOT NULL
);

INSERT INTO seed_permisos (nombre, descripcion, recurso, accion) VALUES
('CREATE_POSTULACIONES', 'Puede registrar postulaciones nuevas', 'POSTULACION', 'CREATE'),
('UPDATE_POSTULACIONES', 'Puede editar y actualizar postulaciones', 'POSTULACION', 'UPDATE'),
('TYPIFY_POSTULACIONES', 'Puede tipificar postulaciones', 'POSTULACION', 'TYPIFY'),
('READ_POSTULACION', 'Puede ver el detalle de una postulacion', 'POSTULACION', 'READ'),
('READ_POSTULACIONES', 'Puede listar postulaciones', 'POSTULACION', 'READ'),
('READ_POSTULACIONES_RECLUTAMIENTO', 'Puede ver la bandeja de postulaciones en reclutamiento', 'POSTULACION', 'READ'),
('READ_POSTULACIONES_CAPACITACION', 'Puede ver la bandeja de postulaciones en capacitacion', 'POSTULACION', 'READ'),
('CONFIRM_CONTRATACION_POSTULACIONES', 'Puede confirmar la contratacion de postulaciones', 'POSTULACION', 'CONFIRM'),
('CREATE_OFERTAS_LABORALES', 'Puede registrar ofertas laborales', 'OFERTA_LABORAL', 'CREATE'),
('UPDATE_OFERTAS_LABORALES', 'Puede registrar ampliaciones de ofertas laborales', 'OFERTA_LABORAL', 'UPDATE'),
('READ_OFERTAS_LABORALES_ACTIVAS', 'Puede listar ofertas laborales activas', 'OFERTA_LABORAL', 'READ'),
('READ_OFERTAS_LABORALES', 'Puede listar y ver ofertas laborales', 'OFERTA_LABORAL', 'READ'),
('UPDATE_ESTADO_OFERTAS_LABORALES', 'Puede cambiar el estado de las ofertas laborales', 'OFERTA_LABORAL', 'UPDATE_ESTADO'),
('CREATE_GRUPOS_CAPACITACION', 'Puede crear grupos de capacitacion', 'GRUPO_CAPACITACION', 'CREATE'),
('READ_GRUPOS_CAPACITACION', 'Puede listar y ver grupos de capacitacion', 'GRUPO_CAPACITACION', 'READ'),
('ASSIGN_GRUPOS_CAPACITACION', 'Puede asignar postulaciones a grupos de capacitacion', 'GRUPO_CAPACITACION', 'ASSIGN'),
('UPDATE_GRUPOS_CAPACITACION', 'Puede actualizar detalles de grupos de capacitacion', 'GRUPO_CAPACITACION', 'UPDATE'),
('READ_EVENTOS_RECRUITMENT', 'Puede ver el historico de eventos de recruitment', 'EVENTO_RECRUITMENT', 'READ'),
('READ_TIPIFICACIONES_RECLUTAMIENTO', 'Puede consultar catalogos de tipificacion de reclutamiento', 'TIPIFICACION_RECLUTAMIENTO', 'READ'),
('READ_TIPIFICACIONES_CAPACITACION', 'Puede consultar catalogos de tipificacion de capacitacion', 'TIPIFICACION_CAPACITACION', 'READ'),
('READ_TIPIFICACIONES_PREVENTA', 'Puede consultar catalogos de tipificacion de preventa', 'TIPIFICACION_PREVENTA', 'READ'),
('READ_TIPIFICACIONES_VENTA', 'Puede consultar catalogos de tipificacion de venta', 'TIPIFICACION_VENTA', 'READ'),
('READ_TIPIFICACIONES_POSTVENTA', 'Puede consultar catalogos de tipificacion de postventa', 'TIPIFICACION_POSTVENTA', 'READ'),
('UPDATE_TIPIFICACIONES', 'Puede actualizar catalogos de tipificacion', 'TIPIFICACION', 'UPDATE'),
('CREATE_EMPLEADOS', 'Puede registrar empleados directamente', 'EMPLEADO', 'CREATE'),
('READ_EMPLEADOS', 'Puede listar y ver empleados', 'EMPLEADO', 'READ'),
('READ_PERSONAL_RECRUITMENT', 'Puede listar personal activo de recruitment', 'EMPLEADO', 'READ'),
('UPDATE_EMPLEADOS', 'Puede editar empleados', 'EMPLEADO', 'UPDATE'),
('BLACKLIST_EMPLEADO', 'Puede marcar como lista negra a los empleados', 'EMPLEADO', 'BLACKLIST'),
('CREATE_CONTRATISTA', 'Puede registrar empresas contratistas', 'EMPRESA_CONTRATISTA', 'CREATE'),
('READ_CONTRATISTAS', 'Puede listar y ver empresas contratistas', 'EMPRESA_CONTRATISTA', 'READ'),
('DELETE_CONTRATISTA', 'Puede desactivar empresas contratistas', 'EMPRESA_CONTRATISTA', 'DELETE'),
('CREATE_CONTRATOS', 'Puede registrar contratos', 'CONTRATO', 'CREATE'),
('UPDATE_CONTRATOS', 'Puede editar contratos', 'CONTRATO', 'UPDATE'),
('READ_CONTRATOS', 'Puede listar y ver contratos', 'CONTRATO', 'READ'),
('CANCEL_CONTRATOS', 'Puede dar de baja contratos', 'CONTRATO', 'CANCEL'),
('CREATE_PAGOS', 'Puede registrar pagos a los empleados', 'PAGO', 'CREATE'),
('UPDATE_PAGOS', 'Puede actualizar informacion de pagos', 'PAGO', 'UPDATE'),
('READ_PAGOS', 'Puede listar y ver informacion de pagos', 'PAGO', 'READ'),
('READ_EVENTOS', 'Puede ver el historico de eventos', 'ENTIDAD', 'READ'),
('CREATE_HORARIOS', 'Puede registrar horarios', 'HORARIO', 'CREATE'),
('READ_HORARIOS', 'Puede listar y consultar horarios', 'HORARIO', 'READ'),
('UPDATE_HORARIOS', 'Puede actualizar horarios y sus excepciones', 'HORARIO', 'UPDATE'),
('READ_ASISTENCIAS_SELF', 'Puede consultar su propia informacion de asistencia', 'ASISTENCIA', 'READ_SELF'),
('READ_ASISTENCIAS', 'Puede consultar asistencia de cualquier empleado autorizado', 'ASISTENCIA', 'READ'),
('READ_ASISTENCIAS_MONITOR', 'Puede consultar estados de asistencia en tiempo real para monitoreo', 'ASISTENCIA', 'READ_MONITOR'),
('READ_ASISTENCIAS_CUMPLIMIENTO', 'Puede consultar cumplimiento de asistencia por periodos y grupos', 'ASISTENCIA', 'READ_COMPLIANCE'),
('UPDATE_ASISTENCIAS', 'Puede registrar movimientos de asistencia', 'ASISTENCIA', 'UPDATE'),
('CREATE_CUENTA_PUBLICITARIA', 'Puede registrar cuentas publicitarias', 'CUENTA_PUBLICITARIA', 'CREATE'),
('READ_CUENTAS_PUBLICITARIAS', 'Puede listar y ver cuentas publicitarias', 'CUENTA_PUBLICITARIA', 'READ'),
('DELETE_CUENTA_PUBLICITARIA', 'Puede desactivar cuentas publicitarias', 'CUENTA_PUBLICITARIA', 'DELETE'),
('CREATE_CAMPANA', 'Puede registrar campanas', 'CAMPANA', 'CREATE'),
('READ_CAMPANA', 'Puede listar y ver campanas', 'CAMPANA', 'READ'),
('UPDATE_CAMPANA', 'Puede actualizar campanas', 'CAMPANA', 'UPDATE'),
('DELETE_CAMPANA', 'Puede desactivar campanas', 'CAMPANA', 'DELETE'),
('CREATE_PROVEEDORES', 'Puede registrar proveedores', 'PROVEEDOR', 'CREATE'),
('READ_PROVEEDORES', 'Puede listar y ver proveedores', 'PROVEEDOR', 'READ'),
('UPDATE_PROVEEDORES', 'Puede actualizar el estado de proveedores', 'PROVEEDOR', 'UPDATE'),
('CREATE_ZONAS', 'Puede registrar zonas', 'ZONA', 'CREATE'),
('READ_ZONAS', 'Puede listar y ver zonas', 'ZONA', 'READ'),
('UPDATE_ZONAS', 'Puede actualizar zonas', 'ZONA', 'UPDATE'),
('READ_UBIGEO', 'Puede consultar ubigeo', 'UBIGEO', 'READ'),
('CREATE_PLANES', 'Puede registrar planes', 'PLAN', 'CREATE'),
('READ_PLANES', 'Puede listar y ver planes', 'PLAN', 'READ'),
('UPDATE_PLANES', 'Puede actualizar planes', 'PLAN', 'UPDATE'),
('DELETE_PLANES', 'Puede desactivar planes', 'PLAN', 'DELETE'),
('CREATE_ADICIONALES', 'Puede registrar adicionales', 'ADICIONAL', 'CREATE'),
('READ_ADICIONALES', 'Puede listar y ver adicionales', 'ADICIONAL', 'READ'),
('CREATE_PROMOCIONES', 'Puede registrar promociones', 'PROMOCION', 'CREATE'),
('READ_PROMOCIONES', 'Puede listar y ver promociones', 'PROMOCION', 'READ'),
('DELETE_PROMOCIONES', 'Puede desactivar promociones', 'PROMOCION', 'DELETE'),
('CREATE_LEADS', 'Puede registrar ingresos de leads', 'LEAD', 'CREATE'),
('ASSIGN_LEADS', 'Puede asignar leads', 'LEAD', 'ASSIGN'),
('READ_LEADS_ASESOR', 'Puede ver bandeja y detalle de leads del asesor', 'LEAD', 'READ'),
('UPDATE_LEADS_ASESOR', 'Puede actualizar datos de gestion del lead', 'LEAD', 'UPDATE'),
('TYPIFY_LEADS', 'Puede tipificar leads', 'LEAD', 'TYPIFY'),
('CONTACT_LEADS', 'Puede registrar contacto de leads', 'LEAD', 'CONTACT'),
('READ_LEADS_GTR', 'Puede ver bandeja de leads para GTR', 'LEAD', 'READ'),
('READ_LEADS_SUPERVISOR_VENTAS_RESUMEN', 'Puede ver resumen de acumuladores de supervisor de ventas', 'LEAD_SUPERVISOR_VENTAS', 'READ'),
('READ_LEADS_SUPERVISOR_VENTAS_BANDEJA', 'Puede ver la bandeja de cualquier asesor para supervisor de ventas', 'LEAD_SUPERVISOR_VENTAS', 'READ'),
('READ_EVENTOS_LEADS', 'Puede ver el historico de eventos de leads', 'EVENTO_LEAD', 'READ');

INSERT INTO permisos (nombre, descripcion, recurso, accion)
SELECT nombre, descripcion, recurso, accion
FROM seed_permisos
ON CONFLICT (nombre) DO UPDATE
SET descripcion = EXCLUDED.descripcion,
    recurso = EXCLUDED.recurso,
    accion = EXCLUDED.accion;

CREATE TEMP TABLE seed_roles (
    nombre TEXT PRIMARY KEY,
    descripcion TEXT NOT NULL
);

INSERT INTO seed_roles (nombre, descripcion) VALUES
('ADMINISTRADOR', 'Gestion completa de Administracion'),
('RRHH', 'Recursos Humanos - Gestion de personal'),
('RECLUTADOR', 'Recursos Humanos - Contacto con postulantes'),
('CAPACITADOR', 'Capacitacion - Gestion de postulantes'),
('COMMUNITY', 'Marketing - Generacion y apoyo comercial'),
('ASESOR_GTR', 'GTR - Asignacion y seguimiento de leads'),
('SUPERVISOR_GTR', 'GTR - Supervision de asignacion de leads'),
('ASESOR_VENTAS', 'Ventas - Gestion de leads asignados'),
('SUPERVISOR_VENTAS', 'Ventas - Supervision de leads asignados'),
('MONITOR', 'Monitoreo - Consulta transversal de la operacion'),
('ASESOR_BACKOFFICE', 'Backoffice - Gestion operativa comercial'),
('SUPERVISOR_BACKOFFICE', 'Backoffice - Supervision operativa comercial'),
('ASESOR_POSTVENTA', 'Postventa - Gestion de cartera y seguimiento'),
('SUPERVISOR_POSTVENTA', 'Postventa - Supervision de cartera y seguimiento'),
('DESARROLLADOR', 'Tecnologia - Soporte y mantenimiento'),
('CONTADOR', 'Contabilidad - Gestion de pagos y consulta laboral');

INSERT INTO roles (nombre, descripcion)
SELECT nombre, descripcion
FROM seed_roles
ON CONFLICT (nombre) DO UPDATE
SET descripcion = EXCLUDED.descripcion;

CREATE TEMP TABLE seed_role_permiso (
    rol_nombre TEXT NOT NULL,
    permiso_nombre TEXT NOT NULL
);

INSERT INTO seed_role_permiso (rol_nombre, permiso_nombre)
SELECT 'ADMINISTRADOR', nombre
FROM seed_permisos;

INSERT INTO seed_role_permiso (rol_nombre, permiso_nombre) VALUES
('RRHH', 'CREATE_POSTULACIONES'),
('RRHH', 'UPDATE_POSTULACIONES'),
('RRHH', 'TYPIFY_POSTULACIONES'),
('RRHH', 'READ_POSTULACION'),
('RRHH', 'READ_POSTULACIONES'),
('RRHH', 'READ_POSTULACIONES_RECLUTAMIENTO'),
('RRHH', 'READ_POSTULACIONES_CAPACITACION'),
('RRHH', 'CONFIRM_CONTRATACION_POSTULACIONES'),
('RRHH', 'CREATE_OFERTAS_LABORALES'),
('RRHH', 'UPDATE_OFERTAS_LABORALES'),
('RRHH', 'READ_OFERTAS_LABORALES'),
('RRHH', 'UPDATE_ESTADO_OFERTAS_LABORALES'),
('RRHH', 'READ_OFERTAS_LABORALES_ACTIVAS'),
('RRHH', 'READ_EVENTOS_RECRUITMENT'),
('RRHH', 'CREATE_EMPLEADOS'),
('RRHH', 'READ_EMPLEADOS'),
('RRHH', 'READ_PERSONAL_RECRUITMENT'),
('RRHH', 'UPDATE_EMPLEADOS'),
('RRHH', 'BLACKLIST_EMPLEADO'),
('RRHH', 'READ_CONTRATISTAS'),
('RRHH', 'CREATE_CONTRATOS'),
('RRHH', 'UPDATE_CONTRATOS'),
('RRHH', 'READ_CONTRATOS'),
('RRHH', 'CANCEL_CONTRATOS'),
('RRHH', 'READ_EVENTOS'),
('RRHH', 'CREATE_HORARIOS'),
('RRHH', 'READ_HORARIOS'),
('RRHH', 'UPDATE_HORARIOS'),
('RRHH', 'READ_ASISTENCIAS_SELF'),
('RRHH', 'READ_ASISTENCIAS'),
('RRHH', 'READ_ASISTENCIAS_CUMPLIMIENTO'),
('RRHH', 'UPDATE_ASISTENCIAS'),
('RECLUTADOR', 'TYPIFY_POSTULACIONES'),
('RECLUTADOR', 'READ_TIPIFICACIONES_RECLUTAMIENTO'),
('RECLUTADOR', 'READ_POSTULACIONES_RECLUTAMIENTO'),
('RECLUTADOR', 'READ_POSTULACION'),
('RECLUTADOR', 'READ_EMPLEADOS'),
('RECLUTADOR', 'READ_PERSONAL_RECRUITMENT'),
('RECLUTADOR', 'CREATE_GRUPOS_CAPACITACION'),
('RECLUTADOR', 'READ_GRUPOS_CAPACITACION'),
('RECLUTADOR', 'ASSIGN_GRUPOS_CAPACITACION'),
('RECLUTADOR', 'UPDATE_GRUPOS_CAPACITACION'),
('RECLUTADOR', 'READ_EVENTOS_RECRUITMENT'),
('RECLUTADOR', 'READ_ASISTENCIAS_SELF'),
('RECLUTADOR', 'UPDATE_ASISTENCIAS'),
('CAPACITADOR', 'READ_GRUPOS_CAPACITACION'),
('CAPACITADOR', 'READ_EVENTOS_RECRUITMENT'),
('CAPACITADOR', 'TYPIFY_POSTULACIONES'),
('CAPACITADOR', 'READ_EMPLEADOS'),
('CAPACITADOR', 'READ_PERSONAL_RECRUITMENT'),
('CAPACITADOR', 'READ_POSTULACIONES_CAPACITACION'),
('CAPACITADOR', 'READ_POSTULACION'),
('CAPACITADOR', 'READ_TIPIFICACIONES_CAPACITACION'),
('CAPACITADOR', 'READ_ASISTENCIAS_SELF'),
('CAPACITADOR', 'UPDATE_ASISTENCIAS'),
('COMMUNITY', 'CREATE_CUENTA_PUBLICITARIA'),
('COMMUNITY', 'READ_CUENTAS_PUBLICITARIAS'),
('COMMUNITY', 'DELETE_CUENTA_PUBLICITARIA'),
('COMMUNITY', 'CREATE_CAMPANA'),
('COMMUNITY', 'READ_CAMPANA'),
('COMMUNITY', 'UPDATE_CAMPANA'),
('COMMUNITY', 'DELETE_CAMPANA'),
('COMMUNITY', 'CREATE_PROVEEDORES'),
('COMMUNITY', 'READ_PROVEEDORES'),
('COMMUNITY', 'UPDATE_PROVEEDORES'),
('COMMUNITY', 'CREATE_ZONAS'),
('COMMUNITY', 'UPDATE_ZONAS'),
('COMMUNITY', 'READ_ZONAS'),
('COMMUNITY', 'READ_UBIGEO'),
('COMMUNITY', 'CREATE_PLANES'),
('COMMUNITY', 'READ_PLANES'),
('COMMUNITY', 'UPDATE_PLANES'),
('COMMUNITY', 'DELETE_PLANES'),
('COMMUNITY', 'CREATE_ADICIONALES'),
('COMMUNITY', 'READ_ADICIONALES'),
('COMMUNITY', 'CREATE_PROMOCIONES'),
('COMMUNITY', 'READ_PROMOCIONES'),
('COMMUNITY', 'DELETE_PROMOCIONES'),
('COMMUNITY', 'READ_ASISTENCIAS_SELF'),
('COMMUNITY', 'UPDATE_ASISTENCIAS'),
('ASESOR_GTR', 'READ_CAMPANA'),
('ASESOR_GTR', 'READ_ZONAS'),
('ASESOR_GTR', 'READ_UBIGEO'),
('ASESOR_GTR', 'READ_PLANES'),
('ASESOR_GTR', 'READ_ADICIONALES'),
('ASESOR_GTR', 'READ_PROMOCIONES'),
('ASESOR_GTR', 'READ_TIPIFICACIONES_PREVENTA'),
('ASESOR_GTR', 'CREATE_LEADS'),
('ASESOR_GTR', 'ASSIGN_LEADS'),
('ASESOR_GTR', 'READ_LEADS_ASESOR'),
('ASESOR_GTR', 'UPDATE_LEADS_ASESOR'),
('ASESOR_GTR', 'TYPIFY_LEADS'),
('ASESOR_GTR', 'CONTACT_LEADS'),
('ASESOR_GTR', 'READ_LEADS_GTR'),
('ASESOR_GTR', 'READ_EVENTOS_LEADS'),
('ASESOR_GTR', 'READ_ASISTENCIAS_MONITOR'),
('ASESOR_GTR', 'READ_ASISTENCIAS_SELF'),
('ASESOR_GTR', 'UPDATE_ASISTENCIAS'),
('SUPERVISOR_GTR', 'READ_LEADS_GTR'),
('SUPERVISOR_GTR', 'ASSIGN_LEADS'),
('SUPERVISOR_GTR', 'READ_EVENTOS_LEADS'),
('SUPERVISOR_GTR', 'READ_CAMPANA'),
('SUPERVISOR_GTR', 'READ_ASISTENCIAS_MONITOR'),
('SUPERVISOR_GTR', 'READ_ASISTENCIAS_SELF'),
('SUPERVISOR_GTR', 'UPDATE_ASISTENCIAS'),
('ASESOR_VENTAS', 'READ_CAMPANA'),
('ASESOR_VENTAS', 'READ_ZONAS'),
('ASESOR_VENTAS', 'READ_UBIGEO'),
('ASESOR_VENTAS', 'READ_PLANES'),
('ASESOR_VENTAS', 'READ_ADICIONALES'),
('ASESOR_VENTAS', 'READ_PROMOCIONES'),
('ASESOR_VENTAS', 'READ_TIPIFICACIONES_PREVENTA'),
('ASESOR_VENTAS', 'READ_LEADS_ASESOR'),
('ASESOR_VENTAS', 'UPDATE_LEADS_ASESOR'),
('ASESOR_VENTAS', 'TYPIFY_LEADS'),
('ASESOR_VENTAS', 'CONTACT_LEADS'),
('ASESOR_VENTAS', 'READ_ASISTENCIAS_SELF'),
('ASESOR_VENTAS', 'UPDATE_ASISTENCIAS'),
('SUPERVISOR_VENTAS', 'READ_CAMPANA'),
('SUPERVISOR_VENTAS', 'READ_ZONAS'),
('SUPERVISOR_VENTAS', 'READ_UBIGEO'),
('SUPERVISOR_VENTAS', 'READ_PLANES'),
('SUPERVISOR_VENTAS', 'READ_ADICIONALES'),
('SUPERVISOR_VENTAS', 'READ_PROMOCIONES'),
('SUPERVISOR_VENTAS', 'READ_TIPIFICACIONES_PREVENTA'),
('SUPERVISOR_VENTAS', 'READ_LEADS_ASESOR'),
('SUPERVISOR_VENTAS', 'UPDATE_LEADS_ASESOR'),
('SUPERVISOR_VENTAS', 'TYPIFY_LEADS'),
('SUPERVISOR_VENTAS', 'CONTACT_LEADS'),
('SUPERVISOR_VENTAS', 'READ_LEADS_GTR'),
('SUPERVISOR_VENTAS', 'READ_LEADS_SUPERVISOR_VENTAS_RESUMEN'),
('SUPERVISOR_VENTAS', 'READ_LEADS_SUPERVISOR_VENTAS_BANDEJA'),
('SUPERVISOR_VENTAS', 'READ_EVENTOS_LEADS'),
('SUPERVISOR_VENTAS', 'READ_ASISTENCIAS_MONITOR'),
('SUPERVISOR_VENTAS', 'READ_ASISTENCIAS_SELF'),
('SUPERVISOR_VENTAS', 'READ_ASISTENCIAS'),
('SUPERVISOR_VENTAS', 'UPDATE_ASISTENCIAS'),
('MONITOR', 'READ_EVENTOS'),
('MONITOR', 'READ_EVENTOS_LEADS'),
('MONITOR', 'READ_EVENTOS_RECRUITMENT'),
('MONITOR', 'READ_EMPLEADOS'),
('MONITOR', 'READ_CONTRATOS'),
('MONITOR', 'READ_POSTULACIONES'),
('MONITOR', 'READ_POSTULACIONES_RECLUTAMIENTO'),
('MONITOR', 'READ_POSTULACIONES_CAPACITACION'),
('MONITOR', 'READ_OFERTAS_LABORALES'),
('MONITOR', 'READ_GRUPOS_CAPACITACION'),
('MONITOR', 'READ_HORARIOS'),
('MONITOR', 'READ_ASISTENCIAS_MONITOR'),
('MONITOR', 'READ_ASISTENCIAS_SELF'),
('MONITOR', 'READ_ASISTENCIAS'),
('MONITOR', 'READ_ASISTENCIAS_CUMPLIMIENTO'),
('ASESOR_BACKOFFICE', 'READ_LEADS_ASESOR'),
('ASESOR_BACKOFFICE', 'UPDATE_LEADS_ASESOR'),
('ASESOR_BACKOFFICE', 'TYPIFY_LEADS'),
('ASESOR_BACKOFFICE', 'CONTACT_LEADS'),
('ASESOR_BACKOFFICE', 'READ_EVENTOS_LEADS'),
('ASESOR_BACKOFFICE', 'READ_PLANES'),
('ASESOR_BACKOFFICE', 'READ_ADICIONALES'),
('ASESOR_BACKOFFICE', 'READ_PROMOCIONES'),
('ASESOR_BACKOFFICE', 'READ_UBIGEO'),
('ASESOR_BACKOFFICE', 'READ_ASISTENCIAS_SELF'),
('ASESOR_BACKOFFICE', 'UPDATE_ASISTENCIAS'),
('SUPERVISOR_BACKOFFICE', 'READ_LEADS_ASESOR'),
('SUPERVISOR_BACKOFFICE', 'UPDATE_LEADS_ASESOR'),
('SUPERVISOR_BACKOFFICE', 'TYPIFY_LEADS'),
('SUPERVISOR_BACKOFFICE', 'CONTACT_LEADS'),
('SUPERVISOR_BACKOFFICE', 'READ_EVENTOS_LEADS'),
('SUPERVISOR_BACKOFFICE', 'READ_PLANES'),
('SUPERVISOR_BACKOFFICE', 'READ_ADICIONALES'),
('SUPERVISOR_BACKOFFICE', 'READ_PROMOCIONES'),
('SUPERVISOR_BACKOFFICE', 'READ_UBIGEO'),
('SUPERVISOR_BACKOFFICE', 'READ_ASISTENCIAS_SELF'),
('SUPERVISOR_BACKOFFICE', 'UPDATE_ASISTENCIAS'),
('ASESOR_POSTVENTA', 'READ_LEADS_ASESOR'),
('ASESOR_POSTVENTA', 'UPDATE_LEADS_ASESOR'),
('ASESOR_POSTVENTA', 'TYPIFY_LEADS'),
('ASESOR_POSTVENTA', 'CONTACT_LEADS'),
('ASESOR_POSTVENTA', 'READ_EVENTOS_LEADS'),
('ASESOR_POSTVENTA', 'READ_PLANES'),
('ASESOR_POSTVENTA', 'READ_ADICIONALES'),
('ASESOR_POSTVENTA', 'READ_PROMOCIONES'),
('ASESOR_POSTVENTA', 'READ_UBIGEO'),
('ASESOR_POSTVENTA', 'READ_ASISTENCIAS_SELF'),
('ASESOR_POSTVENTA', 'UPDATE_ASISTENCIAS'),
('SUPERVISOR_POSTVENTA', 'READ_LEADS_ASESOR'),
('SUPERVISOR_POSTVENTA', 'UPDATE_LEADS_ASESOR'),
('SUPERVISOR_POSTVENTA', 'TYPIFY_LEADS'),
('SUPERVISOR_POSTVENTA', 'CONTACT_LEADS'),
('SUPERVISOR_POSTVENTA', 'READ_EVENTOS_LEADS'),
('SUPERVISOR_POSTVENTA', 'READ_PLANES'),
('SUPERVISOR_POSTVENTA', 'READ_ADICIONALES'),
('SUPERVISOR_POSTVENTA', 'READ_PROMOCIONES'),
('SUPERVISOR_POSTVENTA', 'READ_UBIGEO'),
('SUPERVISOR_POSTVENTA', 'READ_ASISTENCIAS_SELF'),
('SUPERVISOR_POSTVENTA', 'UPDATE_ASISTENCIAS'),
('DESARROLLADOR', 'READ_EVENTOS'),
('DESARROLLADOR', 'READ_EVENTOS_LEADS'),
('DESARROLLADOR', 'READ_EVENTOS_RECRUITMENT'),
('DESARROLLADOR', 'READ_UBIGEO'),
('DESARROLLADOR', 'READ_HORARIOS'),
('DESARROLLADOR', 'READ_ASISTENCIAS_SELF'),
('DESARROLLADOR', 'READ_ASISTENCIAS'),
('CONTADOR', 'READ_EMPLEADOS'),
('CONTADOR', 'READ_CONTRATOS'),
('CONTADOR', 'READ_PAGOS'),
('CONTADOR', 'CREATE_PAGOS'),
('CONTADOR', 'READ_HORARIOS'),
('CONTADOR', 'READ_ASISTENCIAS_SELF'),
('CONTADOR', 'READ_ASISTENCIAS'),
('CONTADOR', 'READ_ASISTENCIAS_CUMPLIMIENTO'),
('CONTADOR', 'UPDATE_ASISTENCIAS');

DELETE FROM rol_permiso rp
USING roles r
WHERE rp.rol_id = r.id
  AND r.nombre IN (SELECT nombre FROM seed_roles)
  AND r.nombre <> 'ADMINISTRADOR';

INSERT INTO rol_permiso (rol_id, permiso_id)
SELECT r.id, p.id
FROM seed_role_permiso srp
JOIN roles r ON r.nombre = srp.rol_nombre
JOIN permisos p ON p.nombre = srp.permiso_nombre
WHERE NOT EXISTS (
    SELECT 1
    FROM rol_permiso rp
    WHERE rp.rol_id = r.id
      AND rp.permiso_id = p.id
);

INSERT INTO usuarios (
    username,
    password,
    email,
    empleado_id,
    dni,
    nombre_completo,
    activo,
    password_inicializada
)
VALUES (
    'admin@albru.admin.pe',
    crypt('albruadminpe', gen_salt('bf')),
    'jevbxx@gmail.com',
    1,
    '76543210',
    'Edinson Vitterio',
    TRUE,
    TRUE
)
ON CONFLICT (username) DO UPDATE
SET password = EXCLUDED.password,
    email = EXCLUDED.email,
    empleado_id = EXCLUDED.empleado_id,
    dni = EXCLUDED.dni,
    nombre_completo = EXCLUDED.nombre_completo,
    activo = EXCLUDED.activo,
    password_inicializada = EXCLUDED.password_inicializada;

INSERT INTO usuario_rol (usuario_id, rol_id)
SELECT u.id, r.id
FROM usuarios u
JOIN roles r ON r.nombre = 'ADMINISTRADOR'
WHERE u.username = 'admin@albru.admin.pe'
  AND NOT EXISTS (
      SELECT 1
      FROM usuario_rol ur
      WHERE ur.usuario_id = u.id
        AND ur.rol_id = r.id
  );
